In [1]:
import pandas as pd
# This Jupyter Notebook Only Has CSV Related Content....

In [3]:
df=pd.read_excel("Sample_Excel.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaT,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaT,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaT,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaT,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaT,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaT,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaT,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaT,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,1970-01-01 05:30:00,NaN,Convert date into a string,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,1900-01-01 13:30:36,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,1970-01-01 05:30:00,NaN,Cutlabel,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,1970-01-01 05:30:00,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,1970-01-01 05:30:00,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,1970-01-01 05:30:00,NaN,NaN,NaN,NaN

# Working with `.xlsx` Files in Pandas

## 1. Reading Excel Files
- `df = pd.read_excel("file.xlsx")` → Reads an Excel file into a DataFrame.
- `df = pd.read_excel("file.xlsx", sheet_name="Sheet1")` → Reads a specific sheet.
- `df = pd.read_excel("file.xlsx", usecols="A:C")` → Reads only specific columns.
- `df = pd.read_excel("file.xlsx", skiprows=3)` → Skips the first 3 rows.
- `df = pd.read_excel("file.xlsx", nrows=10)` → Reads only the first 10 rows.

## 2. Writing to Excel Files
- `df.to_excel("output.xlsx")` → Saves DataFrame to an Excel file.
- `df.to_excel("output.xlsx", index=False)` → Saves without the index column.
- `df.to_excel("output.xlsx", sheet_name="NewSheet")` → Saves to a specific sheet.
- `df.to_excel("output.xlsx", columns=["col1", "col2"])` → Writes only selected columns.

## 3. Working with Multiple Sheets
- `xls = pd.ExcelFile("file.xlsx")` → Loads an Excel file with multiple sheets.
- `df1 = pd.read_excel(xls, sheet_name="Sheet1")` → Reads a specific sheet.
- `df_dict = pd.read_excel("file.xlsx", sheet_name=None)` → Reads all sheets into a dictionary of DataFrames.

## 4. Appending & Merging Data
- `df_existing = pd.read_excel("file.xlsx")`
- `df_combined = pd.concat([df_existing, df_new], ignore_index=True)` → Merges two DataFrames.

## 5. Handling Missing Values in Excel Files
- `df.isnull().sum()` → Counts missing values.
- `df.fillna(value)` → Replaces missing values.
- `df.dropna()` → Removes rows with missing values.

## 6. Checking Excel File Properties
- `df.shape` → Returns `(rows, columns)`.
- `df.dtypes` → Displays data types of all columns.
- `df.describe()` → Provides statistical summary.

Make sure `openpyxl` is installed for `.xlsx` file handling:
```bash
pip install openpyxl